INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('1', 'COMPANY_CREATE');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('2', 'COMPANY_READ');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('3', 'COMPANY_UPDATE');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('4', 'COMPANY_DELETE');
                                        
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('5', 'USER_CREATE');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('6', 'USER_READ');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('7', 'USER_UPDATE');
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('8', 'USER_DELETE');
                                        
INSERT INTO ZAPRIT_AUTHORITY(ID, NAME) VALUES ('9', 'ROLE_COMPANY_READER');