INSERT INTO ZAPRIT_COMPANY(ID, NAME) VALUES ('TestCompanyId1', 'Pepsi');
INSERT INTO ZAPRIT_COMPANY(ID, NAME) VALUES ('TestCompanyId2', 'Coca Cola');
INSERT INTO ZAPRIT_COMPANY(ID, NAME) VALUES ('TestCompanyId3', 'Sprite');