DROP TABLE IF EXISTS ZAPRIT_USER;
CREATE TABLE ZAPRIT_USER (
    ID VARCHAR(40) PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(128) UNIQUE NOT NULL,
    USER_NAME VARCHAR(64) UNIQUE NOT NULL,
    PENDING_EMAIL VARCHAR(128),
    PASSWORD VARCHAR(256),
    FIRST_NAME VARCHAR(128),
    LAST_NAME VARCHAR(128),
    ENABLED BOOL NOT NULL,
    ACCOUNT_NON_EXPIRED BOOL NOT NULL,
    ACCOUNT_NON_LOCKED BOOL NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOL NOT NULL,
    CONFIRMATION_TOKEN VARCHAR(256),
    SIGNUP_TYPE INT NOT NULL,
    COMPANY_ID VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ZAPRIT_AUTHORITY (
   ID VARCHAR(40) NOT NULL,
   NAME VARCHAR(255),
   PRIMARY KEY (ID)
);

ALTER TABLE ZAPRIT_AUTHORITY ADD CONSTRAINT AUTHORITY_NAME UNIQUE(NAME);

CREATE TABLE USERS_AUTHORITIES (
   USER_ID VARCHAR(40) NOT NULL,
   AUTHORITY_ID VARCHAR(40) NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_AUTHORITY FOREIGN KEY (AUTHORITY_ID) REFERENCES ZAPRIT_AUTHORITY;

ALTER TABLE USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_USER_FK  FOREIGN KEY (USER_ID) REFERENCES ZAPRIT_USER;

